### ISSUE TITLE
Hardware health can be negative and < 0% hardware doesn't kill robot

### ISSUE THREAD

**Issue by liamquinn14** [K-B13/Skynet#106]
**Severity**
High

**Priority**
High

**Observed Behaviour**
I've been running an automated test that:
- Logs in to an account with a fresh robot
- Charges to full
- Logs out
- Logs back in
- Charges to full
- Repeat

This test guarantees that hardware eventually reaches 0. 

In the current state of the application, having <= 0 hardware health does not kill the robot.
Furthermore, hardware health can currently fall into negative numbers

<img width="210" alt="Screenshot 2024-12-18 at 11 32 41" src="https://github.com/user-attachments/assets/be82f2a1-07f3-4af1-a0e3-ae9c26d95679" />

**Expected behavior**
Once hardware reaches 0, the robot should die. It should be impossible for there to be negative hardware 

**To Reproduce**
1. Setup repo, sign up, login
2. Create robot
3. Charge robot
4. Log out
5. Log in
6. Charge robot
7. Repeat until hardware reaches <= 0

**Comment by K-B13** [comment]
Think I have fixed this after my hardware fix pull request is merged can you recheck this

**Comment by liamquinn14** [comment]
I've tested this a few times and it works great. Robot now dies on login with either battery and hardware <= 0
