### ISSUE TITLE
In the 'Trivia' game, you can get the answer right every time without even reading the question (unless I'm a genius and didn't know 😂)

### ISSUE THREAD

**Issue by MyrtoG** [K-B13/Skynet#109]
_**Severity**_
Low

_**Priority**_
Medium

_**Observed Behaviour**_
I played Trivia a few times on different levels (easy, medium, hard). Initially, I realised I'm really bad at trivia. Eventually, I found a way to get every answer right, without even reading the question. The reason for that is simple, the correct answer is always option  number 4. Even though I really enjoy pretending I know everything, as a user I now have no motivation to play the game other than seeing the button go green every time. 

_**Expected behaviour**_
As a user, I would like to only get the answer right when I actually know it and have guessed right. I expect the correct answer not to always be in the same place.

_**To Reproduce**_
Steps to reproduce the behaviour:
1. Play 'Trivia' minigame on any level (easy, medium, hard)
2. Pick the fourth option every time without reading the question
3. Notice you always get it right!

_**Additional context**_
**_Important note: I still haven't checked whether the 'correct' answers are actually correct. This would involve a completely different bug report. This bug report still stands on its own, without taking into consideration the validity of the 'correct' answers._**

**Comment by neilstudd** [comment]
Seems like quite an important issue to fix to me - though I also have no doubt that you're a genius 🤓 

https://github.com/K-B13/Skynet/blob/4171b19ad2a8a04da6e4cf1469a38517b4dceaa4/frontend/src/pages/TriviaGame/TriviaGame.jsx#L132-L135
This code always loads all of the incorrect answers, and then the correct answer, hence the correct answer is always last.

Untested, but here's some GPT-generated code which suggests how you might shuffle those answers:

```
// Utility function to shuffle an array
function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
}

// Shuffle the answers
shuffleArray(allAnswers);
```
