### ISSUE TITLE
No differentiation between signup page and login page 

### ISSUE THREAD

**Issue by MyrtoG** [K-B13/Skynet#42]
**Severity**
Low

**Priority**
Low

**Observed Behaviour**
When you signup you are redirected to the login page. Since the two pages are identical, if you don't notice the 'signup' text turning into 'signin' text, you wouldn't know your signup is successful.

**Expected behavior**
The user should have a visual sign letting them  know that they are signed up. Due to time, that could be a message that reads something like 'You have successfully signed up!' and maybe a happy robot celebrating.

**To Reproduce**
1. Sign up using new credentials.
2. Notice that the only thing changing on the page is the text 'signup' to 'signin'.

**Additional context**

**Comment by K-B13** [comment]
Have made it display a message on the login when you signup but have raised the ticket about maybe adding a robot dancing or something like that
