### ISSUE TITLE
No message letting the user know their password is invalid when signing up

### ISSUE THREAD

**Issue by MyrtoG** [K-B13/Skynet#43]
**Severity**
Low

**Priority**
Medium

**Observed Behaviour**
When you try signing up with a password that doesn't meet the requirements, nothing happens. The user could be pressing the 'submit' button again and again wondering what might have gone wrong. 

**Expected behavior**
The user should be informed that the password they are trying to set up is not valid. A message like: 'Invalid password. Password should be at least 8 characters long, contain a letter, a capital letter, a symbol and a number.' would be appropriate.

**To Reproduce**
1. Try to sign up with a valid email address
2. Enter the password '123; into the password field.

**Additional context**

**Comment by K-B13** [comment]
Not sure if it is quite what you meant but it will display why the password or email fails. it is specific so not quite listing the requirements that we are looking for but instead the requirements they are lacking.
