### ISSUE TITLE
No message informing the user they are already signed up

### ISSUE THREAD

**Issue by MyrtoG** [K-B13/Skynet#45]
**Severity**
Low

**Priority**
Low

**Observed Behaviour**
When trying to sign up as an already signed up user, there is no message informing you that you have already signed up. A user could press the 'submit' button again and again with no consequences. This can be confusing for the user.

**Expected behavior**
When you try to sign up with the same credentials as you used to sign up in the past, a message should appear informing you that you are already signed up. Something like: 'You are already signed up! Now go and login and start playing!' An even more fun message could appear to make the user excited to start using the game!

**To Reproduce**
1. Go to sign up page
2. Fill the username with the same email you used to sign up in the past
3. Choose any password

**Additional context**

**Comment by K-B13** [comment]
I now have it so if you try to create a account that exists it should navigate you to login and show a message saying
You already have an account
