### ISSUE TITLE
Add delete account feature

### ISSUE THREAD

**Issue by liamquinn14** [K-B13/Skynet#67]
**Is your feature request related to a problem? Please describe.**
I've noticed that we have a delete user controller in the API, but no way to delete account on the frontend. This would be a great feature so that users can easily delete their personal data. 

**Describe the solution you'd like**
If we can get a profile screen in the Beta, then we could put it there. 

**Describe alternatives you've considered**
Otherwise just anywhere where it's not easy for a user to accidentally click.

**Additional context**
GDPR requires a 'right to erasure' whereby users can request that their data is deleted. This feature would help us in achieving that right.

**Comment by K-B13** [comment]
Think I got this now
