### ISSUE TITLE
Mini games - User has to leave the page and re-enter the game if they want to play again

### ISSUE THREAD

**Issue by MyrtoG** [K-B13/Skynet#68]
_**Severity**_
Low
_**Priority**_
Low

_**Observed Behaviour**_
I played "Battery, Wires and Motherboard" game and I wanted to play it again but there was no option on the page. In order to re-play the game, I had to click the 'go back to robot' button and then choose the game from the main robot page menu again. As a user, the process didn't feel like it was flowing and it felt a bit awkward and unnecessary to have to go back and re-load the game. Since this application is all about fun, I think a more effortless process might be more appropriate.

_**Expected behavior**_
As a User, I expect a button on the page of the game that says _'Play Again'_ or something similar. The button could appear when the game is over (a player reaches 3 points), or it could be on the page as an option the whole time.

_**To Reproduce**_
1. After you have signed-up, created a robot etc, choose the "Battery, Wires and Motherboard" game to play.
2. Play until either you or the robot wins (scores 3 points).

**Comment by MyrtoG** [comment]
Same behaviour was observed for all the mini games.

**Comment by K-B13** [comment]
We think we might have a navigate to the games page instead of a replay button it makes cleanup a bit easier and is only 1 extra click
