### ISSUE TITLE
Mini games - User doesn't know how much they have earned in currency every time they win a game

### ISSUE THREAD

**Issue by MyrtoG** [K-B13/Skynet#76]
_**Severity**_
Low

_**Priority**_
Medium

_**Observed Behaviour**_
I played two mini games so far and I didn't even realise I was earning currency. This takes away from my experience as I don't have a real motive to play the games. Playing the games will give me currency which I will then spend on my robot. If it's not clear that I earn money when I win, then I might quickly get bored and not bother with playing the games any longer.

_**Expected behavior**_
I expect to see a message saying "_You've earned (x amount)$ ! Hooray!_" or something similar, every time I win. Additionally, a message saying "_You didn't earn any $ this time. Keep trying! Your robot needs you!_" Or something similar.

_**To Reproduce**_
1. Play any game until you win
2. Notice the only way of knowing if you've earned any money is by checking your money before and after the win.

**Comment by K-B13** [comment]
Fixed this for BWAM

**Comment by K-B13** [comment]
Fixed this for NAB
