### ISSUE TITLE
Buttons for "Battery, Wires and Motherboard" and "Nutz and Boltz" are not descriptive at all

### ISSUE THREAD

**Issue by MyrtoG** [K-B13/Skynet#77]
_**Severity**_
Low

_**Priority**_
Medium

_**Observed Behaviour**_
The buttons to play the "Battery, Wires and Motherboard" and "Nutz and Boltz" games are 'BWAM' and 'NAB' respectively. As a user, I have no idea what the purpose of these buttons is and might ignore them altogether.

_**Expected behavior**_
As a user, I expect the button to be more descriptive so that I know its purpose. Something like "_Play Battery, Wires and Motherboard_" and "_Play Nutz and Boltz_" would be more appropriate. The word 'play' is also inviting for the user.

_**To Reproduce**_
1. Go on the main robot page
2. Notice the two buttons with names 'BWAM' and 'NAB' respectively

**Comment by K-B13** [comment]
Have added instructions on what to do on Battery, Wires and Motherboard. I have also added the names of each action underneath the image

**Comment by MyrtoG** [comment]
I'm closing this as we now have a whole game page that looks great
