### ISSUE TITLE
Cannot earn money while battery is 100%

### ISSUE THREAD

**Issue by liamquinn14** [K-B13/Skynet#84]
**Severity**
High

**Priority**
High

**Observed Behaviour**
While battery is 100%, I cannot earn any currency. 
- The add cash button only works when battery < 100%
- Winning minigames only earns currency when battery < 100%

**Expected behavior**
Users should be able to earn currency regardless of battery life

**To Reproduce**
1. Setup repo, sign up, login
2. Create robot
3. Ensure you have 100% battery and take note of your currency
4. Press 'ADD CASH'
5. Win a minigame
6. See if currency has increased

**Additional context**
Removing an unnecessary if statement in api/controllers/robot.js updateRobotCurrency function should resolve this, but may require refactoring elsewhere
Removing the if statement reintroduces bug where users pay for increased battery despite being on 100%

**Comment by K-B13** [comment]
I think we can maybe solve this by adding an and to the if where if curency passed into the route is less than 0. I think this route is only used to reduce money on the energy buttons if this is the case this should fix it I think. But will need to clarify this with others at 14.00

**Comment by K-B13** [comment]
Think Kelly has fixed this with the above fix
