### ISSUE TITLE
Mood is blank until first user action

### ISSUE THREAD

**Issue by liamquinn14** [K-B13/Skynet#87]
**Severity**
Low

**Priority**
Low

**Observed Behaviour**
After creating a robot, the user is navigated to the landing page. Here they can see their robot's stats, e.g. battery, hardware etc.
However mood is blank until the user performs an action, e.g. charge, teach

![Screenshot 2024-12-17 at 12 26 03](https://github.com/user-attachments/assets/54e9b4f3-55a5-41f2-a7e9-22eb09cf963d)

**Expected behavior**
The mood should start at 'happy' since battery and hardware are at 100% with new robots.

**To Reproduce**
1. Setup repo, sign up and login
2. Create robot
3. View 'mood' in robot stats

**Comment by K-B13** [comment]
Think this is fixed
